export default async function Page() {
  return (
    <>
      {/* page */}
      <div className="mx-auto flex w-full max-w-screen-sm flex-col space-y-4 px-4 py-12 font-sans text-primary dark:text-secondary-focus-dark">
        <h1 className="pb-3 text-4xl font-semibold text-primary dark:text-primary-dark">
          About
        </h1>
        <p>
          The following contents were generated by{" "}
          <a
            href="https://gemini.google.com/"
            target="_blank"
            className="underline decoration-2 underline-offset-2"
          >
            Google Gemini
          </a>
          .
        </p>
        <p>
          The New York City public school system, overseen by the New York City
          Department of Education (NYCDOE), is the largest in the United States,
          with over 1.1 million students in more than 1,700 schools.
        </p>
        <p>Here&apos;s a quick breakdown of the NYC school system:</p>
        <p className="pl-4">
          - <span className="font-semibold">Public Schools</span> (managed by
          NYCDOE): Over 1,700 schools, serving over 1.1 million students
        </p>
        <p className="pl-4">
          - <span className="font-semibold">Charter Schools</span>: Publicly
          funded schools that operate independently
        </p>
        <p className="pl-4">
          - <span className="font-semibold">Private Schools</span>: Secular and
          religious schools operated privately
        </p>
        <p>
          You can find a school for your child by searching on the NYC
          Department of Education website{" "}
          <a
            href="https://schoolsearch.schools.nyc/"
            target="_blank"
            className="underline underline-offset-2 hover:text-secondary-focus dark:hover:text-secondary-focus"
          >
            https://schoolsearch.schools.nyc/
          </a>
          .
        </p>
      </div>
    </>
  );
}
